version: "3.8"

services:
  backend:
    build: ./backend
    networks:
      - backend_network
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  worker:
    build: ./worker
    networks:
      - backend_network
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:latest
    networks:
      - backend_network

  db:
    image: postgres:13
    networks:
      - backend_network
    environment:
      POSTGRES_DB: feedbackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  backend_network:

volumes:
  db_data:

