version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - backend_network
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_PASSWORD: secret
    command: sh -c  "python app.py"

  worker:
    build: ./worker
    container_name: worker
    networks:
      - backend_network
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_PASSWORD: secret

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend_network

  db:
    image: postgres:13
    container_name: db
    networks:
      - backend_network
    environment:
      POSTGRES_DB: feedbackdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  backend_network:

volumes:
  db_data:

secrets:
  db_password:
    file: db_password.txt

